import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
	container: {
		flex: 1,
		backgroundColor: '#F9FAFB',
	},
	header: {
		flexDirection: 'row',
		alignItems: 'center',
		justifyContent: 'space-between',
		paddingHorizontal: 16,
		paddingTop: 60,
		paddingBottom: 16,
		backgroundColor: '#FFFFFF',
		borderBottomWidth: 1,
		borderBottomColor: '#E5E7EB',
	},
	backButton: {
		width: 40,
		height: 40,
		borderRadius: 20,
		backgroundColor: '#F3F4F6',
		alignItems: 'center',
		justifyContent: 'center',
	},
	headerCenter: {
		flex: 1,
		alignItems: 'center',
	},
	headerTitle: {
		fontSize: 18,
		fontWeight: '700',
		color: '#032B3C',
	},
	headerSubtitle: {
		fontSize: 12,
		color: '#6B7280',
		marginTop: 2,
	},
	progressContainer: {
		height: 4,
		backgroundColor: '#E5E7EB',
	},
	progressBar: {
		height: '100%',
		backgroundColor: '#0B729D',
	},
	content: {
		flex: 1,
		paddingHorizontal: 16,
	},
	sectionTitle: {
		fontSize: 20,
		fontWeight: '700',
		color: '#032B3C',
		marginTop: 24,
		marginBottom: 16,
	},
	inputGroup: {
		marginBottom: 20,
	},
	label: {
		fontSize: 14,
		fontWeight: '600',
		color: '#374151',
		marginBottom: 8,
	},
	input: {
		backgroundColor: '#FFFFFF',
		borderWidth: 1,
		borderColor: '#D1D5DB',
		borderRadius: 12,
		paddingHorizontal: 16,
		paddingVertical: 14,
		fontSize: 16,
		color: '#032B3C',
	},
	textArea: {
		height: 100,
		textAlignVertical: 'top',
	},
	row: {
		flexDirection: 'row',
		marginBottom: 20,
	},
	chipsContainer: {
		flexDirection: 'row',
		marginTop: 4,
	},
	chip: {
		backgroundColor: '#FFFFFF',
		borderWidth: 1,
		borderColor: '#D1D5DB',
		borderRadius: 20,
		paddingHorizontal: 16,
		paddingVertical: 8,
		marginRight: 8,
	},
	chipSelected: {
		backgroundColor: '#0B729D',
		borderColor: '#0B729D',
	},
	chipText: {
		fontSize: 14,
		color: '#6B7280',
		fontWeight: '500',
	},
	chipTextSelected: {
		color: '#FFFFFF',
	},
	optionsRow: {
		flexDirection: 'row',
		gap: 12,
	},
	optionCard: {
		flex: 1,
		backgroundColor: '#FFFFFF',
		borderWidth: 1,
		borderColor: '#D1D5DB',
		borderRadius: 12,
		padding: 16,
		alignItems: 'center',
		justifyContent: 'center',
		gap: 8,
	},
	optionCardSelected: {
		borderColor: '#0B729D',
		borderWidth: 2,
		backgroundColor: '#EFF6FF',
	},
	optionText: {
		fontSize: 14,
		color: '#6B7280',
		fontWeight: '500',
	},
	optionTextSelected: {
		color: '#0B729D',
		fontWeight: '600',
	},
	footer: {
		backgroundColor: '#FFFFFF',
		paddingHorizontal: 16,
		paddingTop: 16,
		paddingBottom: 32,
		borderTopWidth: 1,
		borderTopColor: '#E5E7EB',
	},
	nextButton: {
		backgroundColor: '#0B729D',
		borderRadius: 12,
		paddingVertical: 16,
		flexDirection: 'row',
		alignItems: 'center',
		justifyContent: 'center',
		gap: 8,
	},
	nextButtonDisabled: {
		backgroundColor: '#9CA3AF',
		opacity: 0.6,
	},
	nextButtonText: {
		color: '#FFFFFF',
		fontSize: 16,
		fontWeight: '700',
	},
	photoPlaceholder: {
		width: '100%',
		height: 200,
		backgroundColor: '#F3F4F6',
		borderWidth: 2,
		borderColor: '#D1D5DB',
		borderStyle: 'dashed',
		borderRadius: 12,
		alignItems: 'center',
		justifyContent: 'center',
		marginBottom: 16,
		overflow: 'hidden',
	},
	photoPlaceholderText: {
		marginTop: 8,
		color: '#6B7280',
		fontSize: 14,
	},
	uploadedPhoto: {
		width: '100%',
		height: '100%',
		resizeMode: 'cover',
	},
	editPhotoOverlay: {
		position: 'absolute',
		bottom: 8,
		right: 8,
		backgroundColor: 'rgba(0,0,0,0.6)',
		borderRadius: 20,
		padding: 8,
	},
});
