import { Platform, StatusBar, StyleSheet } from 'react-native';

const STATUSBAR_HEIGHT = Platform.OS === 'ios' ? 48 : StatusBar.currentHeight || 0;

export const styles = StyleSheet.create({
	container: {
		flex: 1,
		backgroundColor: '#F9FAFB',
	},
	header: {
		flexDirection: 'row',
		alignItems: 'center',
		justifyContent: 'space-between',
		paddingHorizontal: 16,
		paddingTop: STATUSBAR_HEIGHT + 10,
		paddingBottom: 16,
		backgroundColor: '#FFFFFF',
		borderBottomWidth: 1,
		borderBottomColor: '#E5E7EB',
	},
	backButton: {
		width: 40,
		height: 40,
		borderRadius: 20,
		backgroundColor: '#F3F4F6',
		alignItems: 'center',
		justifyContent: 'center',
	},
	headerCenter: {
		flex: 1,
		alignItems: 'center',
	},
	headerTitle: {
		fontSize: 18,
		fontWeight: '700',
		color: '#032B3C',
	},
	headerSubtitle: {
		fontSize: 12,
		color: '#6B7280',
		marginTop: 2,
	},
	progressContainer: {
		height: 4,
		backgroundColor: '#E5E7EB',
		position: 'relative',
	},
	progressBar: {
		height: '100%',
		backgroundColor: '#0B729D',
		borderRadius: 2,
	},
	progressTextContainer: {
		position: 'absolute',
		top: 8,
		right: 16,
	},
	progressText: {
		fontSize: 11,
		color: '#6B7280',
		fontWeight: '600',
	},
	content: {
		flex: 1,
		paddingHorizontal: 16,
	},
	sectionTitle: {
		fontSize: 20,
		fontWeight: '700',
		color: '#032B3C',
		marginTop: 24,
		marginBottom: 16,
	},
	inputGroup: {
		marginBottom: 20,
	},
	label: {
		fontSize: 14,
		fontWeight: '600',
		color: '#374151',
		marginBottom: 8,
	},
	input: {
		backgroundColor: '#FFFFFF',
		borderWidth: 1,
		borderColor: '#D1D5DB',
		borderRadius: 12,
		paddingHorizontal: 16,
		paddingVertical: 14,
		fontSize: 16,
		color: '#032B3C',
	},
	textArea: {
		height: 100,
		textAlignVertical: 'top',
	},
	row: {
		flexDirection: 'row',
		marginBottom: 20,
	},
	chipsContainer: {
		flexDirection: 'row',
		marginTop: 4,
	},
	chip: {
		backgroundColor: '#FFFFFF',
		borderWidth: 1,
		borderColor: '#D1D5DB',
		borderRadius: 20,
		paddingHorizontal: 16,
		paddingVertical: 8,
		marginRight: 8,
	},
	chipSelected: {
		backgroundColor: '#0B729D',
		borderColor: '#0B729D',
	},
	chipText: {
		fontSize: 14,
		color: '#6B7280',
		fontWeight: '500',
	},
	chipTextSelected: {
		color: '#FFFFFF',
	},
	optionsRow: {
		flexDirection: 'row',
		gap: 12,
	},
	optionCard: {
		flex: 1,
		backgroundColor: '#FFFFFF',
		borderWidth: 1,
		borderColor: '#D1D5DB',
		borderRadius: 12,
		padding: 16,
		alignItems: 'center',
		justifyContent: 'center',
		gap: 8,
	},
	optionCardSelected: {
		borderColor: '#0B729D',
		borderWidth: 2,
		backgroundColor: '#EFF6FF',
	},
	optionText: {
		fontSize: 14,
		color: '#6B7280',
		fontWeight: '500',
	},
	optionTextSelected: {
		color: '#0B729D',
		fontWeight: '600',
	},
	footer: {
		backgroundColor: '#FFFFFF',
		paddingHorizontal: 16,
		paddingTop: 16,
		paddingBottom: 32,
		borderTopWidth: 1,
		borderTopColor: '#E5E7EB',
	},
	nextButton: {
		backgroundColor: '#0B729D',
		borderRadius: 12,
		paddingVertical: 16,
		flexDirection: 'row',
		alignItems: 'center',
		justifyContent: 'center',
		gap: 8,
	},
	nextButtonDisabled: {
		backgroundColor: '#9CA3AF',
		opacity: 0.6,
	},
	nextButtonText: {
		color: '#FFFFFF',
		fontSize: 16,
		fontWeight: '700',
	},
	photoPlaceholder: {
		width: '100%',
		height: 200,
		backgroundColor: '#F3F4F6',
		borderWidth: 2,
		borderColor: '#D1D5DB',
		borderStyle: 'dashed',
		borderRadius: 12,
		alignItems: 'center',
		justifyContent: 'center',
		marginBottom: 16,
		overflow: 'hidden',
	},
	photoPlaceholderText: {
		marginTop: 8,
		color: '#6B7280',
		fontSize: 14,
	},
	uploadedPhoto: {
		width: '100%',
		height: '100%',
		resizeMode: 'cover',
	},
	editPhotoOverlay: {
		position: 'absolute',
		bottom: 8,
		right: 8,
		backgroundColor: 'rgba(0,0,0,0.6)',
		borderRadius: 20,
		padding: 8,
	},
	photoCheckmark: {
		position: 'absolute',
		top: 8,
		right: 8,
		backgroundColor: 'white',
		borderRadius: 16,
	},
	photoPreviewBadge: {
		position: 'absolute',
		bottom: 8,
		left: 8,
		backgroundColor: 'rgba(11, 114, 157, 0.9)',
		borderRadius: 12,
		padding: 6,
	},
	locationSection: {
		marginBottom: 20,
		backgroundColor: '#FFFFFF',
		borderRadius: 12,
		padding: 16,
		borderWidth: 1,
		borderColor: '#E5E7EB',
	},
	// Estilos de validación
	inputError: {
		borderColor: '#DC2626',
		borderWidth: 2,
		backgroundColor: '#FEF2F2',
	},
	inputSuccess: {
		borderColor: '#16A34A',
		borderWidth: 2,
		backgroundColor: '#F0FDF4',
	},
	errorContainer: {
		flexDirection: 'row',
		alignItems: 'center',
		gap: 6,
		marginTop: 6,
	},
	errorText: {
		fontSize: 13,
		color: '#DC2626',
		fontWeight: '500',
	},
	errorTextSmall: {
		fontSize: 11,
		color: '#DC2626',
		marginTop: 4,
		fontWeight: '500',
	},
	successContainer: {
		flexDirection: 'row',
		alignItems: 'center',
		gap: 6,
		marginTop: 6,
	},
	successText: {
		fontSize: 13,
		color: '#16A34A',
		fontWeight: '500',
	},
	// Vista previa
	previewCard: {
		backgroundColor: '#FFFFFF',
		borderRadius: 12,
		padding: 16,
		marginBottom: 24,
		borderWidth: 1,
		borderColor: '#E5E7EB',
		shadowColor: '#000',
		shadowOffset: { width: 0, height: 2 },
		shadowOpacity: 0.05,
		shadowRadius: 4,
		elevation: 2,
	},
	previewHeader: {
		flexDirection: 'row',
		alignItems: 'center',
		gap: 8,
		marginBottom: 12,
		paddingBottom: 12,
		borderBottomWidth: 1,
		borderBottomColor: '#F3F4F6',
	},
	previewTitle: {
		fontSize: 13,
		fontWeight: '600',
		color: '#0B729D',
		textTransform: 'uppercase',
		letterSpacing: 0.5,
	},
	previewContent: {
		gap: 8,
	},
	previewVehicleName: {
		fontSize: 18,
		fontWeight: '700',
		color: '#032B3C',
	},
	previewBadge: {
		flexDirection: 'row',
		alignItems: 'center',
		gap: 6,
		backgroundColor: '#F3F4F6',
		paddingHorizontal: 10,
		paddingVertical: 6,
		borderRadius: 8,
		alignSelf: 'flex-start',
	},
	previewPlate: {
		fontSize: 13,
		color: '#6B7280',
		fontWeight: '600',
	},
	// Tooltips y ayuda
	headerWithTooltip: {
		flexDirection: 'row',
		alignItems: 'center',
		justifyContent: 'space-between',
		marginTop: 24,
		marginBottom: 16,
	},
	tooltipButton: {
		width: 32,
		height: 32,
		borderRadius: 16,
		backgroundColor: '#EFF6FF',
		alignItems: 'center',
		justifyContent: 'center',
	},
	tooltipCard: {
		flexDirection: 'row',
		backgroundColor: '#EFF6FF',
		borderLeftWidth: 3,
		borderLeftColor: '#0B729D',
		borderRadius: 8,
		padding: 12,
		marginBottom: 20,
		gap: 8,
	},
	tooltipText: {
		flex: 1,
		fontSize: 13,
		color: '#1E40AF',
		lineHeight: 18,
	},
	// Contador de caracteres
	charCounterContainer: {
		flexDirection: 'row',
		justifyContent: 'space-between',
		alignItems: 'center',
		marginTop: 6,
	},
	charCounter: {
		fontSize: 12,
		fontWeight: '500',
	},
	charCounterNormal: {
		color: '#6B7280',
	},
	charCounterWarning: {
		color: '#F59E0B',
	},
	charCounterDanger: {
		color: '#DC2626',
	},
	charCounterSuccess: {
		color: '#16A34A',
	},
	// Modal de Éxito
	successModalOverlay: {
		flex: 1,
		backgroundColor: 'rgba(0, 0, 0, 0.5)',
		justifyContent: 'center',
		alignItems: 'center',
	},
	successModalContent: {
		backgroundColor: 'white',
		borderRadius: 20,
		padding: 32,
		alignItems: 'center',
		width: '80%',
		maxWidth: 320,
	},
	successIconCircle: {
		width: 100,
		height: 100,
		borderRadius: 50,
		backgroundColor: '#D1FAE5',
		justifyContent: 'center',
		alignItems: 'center',
		marginBottom: 20,
	},
	successModalTitle: {
		fontSize: 24,
		fontWeight: '700',
		color: '#1F2937',
		marginBottom: 8,
		textAlign: 'center',
	},
	successModalText: {
		fontSize: 15,
		color: '#6B7280',
		textAlign: 'center',
	},
	// Comparación de precios
	priceComparisonCard: {
		marginTop: 12,
		padding: 12,
		borderRadius: 8,
		borderWidth: 1,
	},
	priceComparisonTitle: {
		fontSize: 13,
		fontWeight: '600',
	},
	// Banner de Bienvenida
	welcomeBanner: {
		flexDirection: 'row',
		backgroundColor: '#EFF6FF',
		borderRadius: 16,
		padding: 20,
		marginTop: 16,
		marginBottom: 16,
		borderWidth: 2,
		borderColor: '#0B729D',
		shadowColor: '#0B729D',
		shadowOffset: { width: 0, height: 4 },
		shadowOpacity: 0.1,
		shadowRadius: 8,
		elevation: 4,
	},
	welcomeIconContainer: {
		width: 56,
		height: 56,
		borderRadius: 28,
		backgroundColor: '#FFFFFF',
		justifyContent: 'center',
		alignItems: 'center',
		marginRight: 16,
	},
	welcomeContent: {
		flex: 1,
		justifyContent: 'center',
	},
	welcomeTitle: {
		fontSize: 20,
		fontWeight: '700',
		color: '#032B3C',
		marginBottom: 4,
	},
	welcomeSubtitle: {
		fontSize: 14,
		color: '#6B7280',
		fontWeight: '500',
	},
	newBadge: {
		backgroundColor: '#10B981',
		paddingHorizontal: 8,
		paddingVertical: 3,
		borderRadius: 6,
	},
	newBadgeText: {
		fontSize: 10,
		fontWeight: '800',
		color: '#FFFFFF',
		letterSpacing: 0.5,
	},
	inputError: {
		borderColor: '#EF4444',
		borderWidth: 2,
	},
	inputSuccess: {
		borderColor: '#10B981',
		borderWidth: 2,
	},
	inputIconRight: {
		position: 'absolute',
		right: 12,
		top: 14,
	},
	tooltipCard: {
		flexDirection: 'row',
		backgroundColor: '#EFF6FF',
		padding: 12,
		borderRadius: 8,
		marginBottom: 16,
		gap: 8,
		borderWidth: 1,
		borderColor: '#0B729D',
	},
	tooltipText: {
		flex: 1,
		fontSize: 13,
		color: '#1E40AF',
		lineHeight: 18,
	},
	ruleItem: {
		flexDirection: 'row',
		alignItems: 'center',
		justifyContent: 'space-between',
		paddingVertical: 12,
		borderBottomWidth: 1,
		borderBottomColor: '#E5E7EB',
	},
	depositTypeButton: {
		flex: 1,
		paddingVertical: 12,
		paddingHorizontal: 16,
		borderRadius: 10,
		borderWidth: 1.5,
		borderColor: '#D1D5DB',
		backgroundColor: '#FFFFFF',
		alignItems: 'center',
	},
	depositTypeButtonActive: {
		borderColor: '#032B3C',
		backgroundColor: '#EFF6FF',
	},
	depositTypeText: {
		fontSize: 13,
		fontWeight: '600',
		color: '#6B7280',
	},
	depositTypeTextActive: {
		color: '#032B3C',
	},
});