export interface Vehicle {
  id: string;
  marca: string;
  modelo: string;
  anio: number;
  precio: number; // precio por día en USD
  precioOriginal?: number; // si hay descuento
  ubicacion: string;
  coordinates?: { latitude: number; longitude: number }; // Coordenadas GPS
  distancia?: number; // km desde el usuario (calculado dinámicamente)
  distanceText?: string; // Texto formateado de distancia
  imagen: string;
  imagenes?: string[]; // para carousel
  rating: number; // 0-5
  reviewCount: number;
  transmision: 'Automático' | 'Manual';
  combustible: 'Gasolina' | 'Diesel' | 'Híbrido' | 'Eléctrico';
  pasajeros: number;
  puertas: number;
  tipo: 'Sedán' | 'SUV' | 'Pickup' | 'Hatchback' | 'Minivan';
  caracteristicas: string[]; // ['A/C', 'Bluetooth', 'GPS', etc.]
  badges?: ('Nuevo' | 'Más rentado' | 'Descuento' | 'Disponible hoy' | 'Verificado')[];
  disponible: boolean;
  propietarioId: string;
}

export const MOCK_VEHICLES: Vehicle[] = [
  {
    id: '1',
    marca: 'Toyota',
    modelo: 'Corolla',
    anio: 2023,
    precio: 25,
    precioOriginal: 30,
    ubicacion: 'San Salvador',
    distancia: 2.3,
    imagen: 'https://images.unsplash.com/photo-1623869675781-80aa31f198c7?w=800&q=80',
    imagenes: [
      'https://images.unsplash.com/photo-1623869675781-80aa31f198c7?w=800&q=80',
      'https://images.unsplash.com/photo-1621939514649-280e2ee25f60?w=800&q=80',
    ],
    rating: 4.8,
    reviewCount: 124,
    transmision: 'Automático',
    combustible: 'Gasolina',
    pasajeros: 5,
    puertas: 4,
    tipo: 'Sedán',
    caracteristicas: ['A/C', 'Bluetooth', 'Cámara reversa', 'USB'],
    badges: ['Descuento', 'Más rentado', 'Verificado'],
    disponible: true,
    propietarioId: 'owner1',
  },
  {
    id: '2',
    marca: 'Honda',
    modelo: 'CR-V',
    anio: 2024,
    precio: 45,
    ubicacion: 'Santa Tecla',
    distancia: 5.1,
    imagen: 'https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?w=800&q=80',
    rating: 4.9,
    reviewCount: 87,
    transmision: 'Automático',
    combustible: 'Híbrido',
    pasajeros: 5,
    puertas: 4,
    tipo: 'SUV',
    caracteristicas: ['A/C', 'GPS', 'Bluetooth', 'Apple CarPlay', 'Cámara 360°'],
    badges: ['Nuevo', 'Disponible hoy', 'Verificado'],
    disponible: true,
    propietarioId: 'owner2',
  },
  {
    id: '3',
    marca: 'Nissan',
    modelo: 'Sentra',
    anio: 2022,
    precio: 28,
    ubicacion: 'Antiguo Cuscatlán',
    distancia: 3.7,
    imagen: 'https://images.unsplash.com/photo-1619767886558-efdc259cde1a?w=800&q=80',
    rating: 4.6,
    reviewCount: 56,
    transmision: 'Automático',
    combustible: 'Gasolina',
    pasajeros: 5,
    puertas: 4,
    tipo: 'Sedán',
    caracteristicas: ['A/C', 'Bluetooth', 'USB'],
    badges: ['Verificado'],
    disponible: true,
    propietarioId: 'owner3',
  },
  {
    id: '4',
    marca: 'Hyundai',
    modelo: 'Tucson',
    anio: 2023,
    precio: 40,
    precioOriginal: 48,
    ubicacion: 'San Salvador',
    distancia: 1.8,
    imagen: 'https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?w=800&q=80',
    rating: 4.7,
    reviewCount: 92,
    transmision: 'Automático',
    combustible: 'Gasolina',
    pasajeros: 5,
    puertas: 4,
    tipo: 'SUV',
    caracteristicas: ['A/C', 'GPS', 'Bluetooth', 'Cámara reversa', 'Sensor de estacionamiento'],
    badges: ['Descuento', 'Más rentado'],
    disponible: true,
    propietarioId: 'owner1',
  },
  {
    id: '5',
    marca: 'Mazda',
    modelo: 'CX-5',
    anio: 2024,
    precio: 50,
    ubicacion: 'Santa Tecla',
    distancia: 4.2,
    imagen: 'https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?w=800&q=80',
    rating: 5.0,
    reviewCount: 43,
    transmision: 'Automático',
    combustible: 'Gasolina',
    pasajeros: 5,
    puertas: 4,
    tipo: 'SUV',
    caracteristicas: ['A/C', 'GPS', 'Bluetooth', 'Apple CarPlay', 'Android Auto', 'Asientos de cuero'],
    badges: ['Nuevo', 'Verificado'],
    disponible: true,
    propietarioId: 'owner4',
  },
  {
    id: '6',
    marca: 'Kia',
    modelo: 'Rio',
    anio: 2021,
    precio: 22,
    ubicacion: 'Soyapango',
    distancia: 7.5,
    imagen: 'https://images.unsplash.com/photo-1583121274602-3e2820c69888?w=800&q=80',
    rating: 4.4,
    reviewCount: 67,
    transmision: 'Manual',
    combustible: 'Gasolina',
    pasajeros: 5,
    puertas: 4,
    tipo: 'Sedán',
    caracteristicas: ['A/C', 'Bluetooth'],
    badges: ['Verificado'],
    disponible: true,
    propietarioId: 'owner5',
  },
  {
    id: '7',
    marca: 'Ford',
    modelo: 'Escape',
    anio: 2023,
    precio: 42,
    ubicacion: 'Antiguo Cuscatlán',
    distancia: 3.1,
    imagen: 'https://images.unsplash.com/photo-1511919884226-fd3cad34687c?w=800&q=80',
    rating: 4.7,
    reviewCount: 78,
    transmision: 'Automático',
    combustible: 'Gasolina',
    pasajeros: 5,
    puertas: 4,
    tipo: 'SUV',
    caracteristicas: ['A/C', 'GPS', 'Bluetooth', 'Apple CarPlay', 'Cámara reversa'],
    badges: ['Disponible hoy', 'Verificado'],
    disponible: true,
    propietarioId: 'owner2',
  },
  {
    id: '8',
    marca: 'Chevrolet',
    modelo: 'Spark',
    anio: 2020,
    precio: 18,
    ubicacion: 'San Salvador',
    distancia: 2.9,
    imagen: 'https://images.unsplash.com/photo-1552519507-da3b142c6e3d?w=800&q=80',
    rating: 4.3,
    reviewCount: 34,
    transmision: 'Manual',
    combustible: 'Gasolina',
    pasajeros: 4,
    puertas: 4,
    tipo: 'Hatchback',
    caracteristicas: ['A/C', 'Bluetooth'],
    badges: [],
    disponible: true,
    propietarioId: 'owner6',
  },
  {
    id: '9',
    marca: 'Toyota',
    modelo: 'RAV4',
    anio: 2024,
    precio: 55,
    ubicacion: 'Santa Tecla',
    distancia: 4.8,
    imagen: 'https://images.unsplash.com/photo-1566024287286-457247b70310?w=800&q=80',
    rating: 4.9,
    reviewCount: 156,
    transmision: 'Automático',
    combustible: 'Híbrido',
    pasajeros: 5,
    puertas: 4,
    tipo: 'SUV',
    caracteristicas: ['A/C', 'GPS', 'Bluetooth', 'Apple CarPlay', 'Android Auto', 'Cámara 360°', 'Asientos de cuero'],
    badges: ['Nuevo', 'Más rentado', 'Verificado'],
    disponible: true,
    propietarioId: 'owner1',
  },
  {
    id: '10',
    marca: 'Volkswagen',
    modelo: 'Jetta',
    anio: 2022,
    precio: 32,
    ubicacion: 'San Salvador',
    distancia: 1.5,
    imagen: 'https://images.unsplash.com/photo-1563720360172-67b8f3dce741?w=800&q=80',
    rating: 4.6,
    reviewCount: 89,
    transmision: 'Automático',
    combustible: 'Gasolina',
    pasajeros: 5,
    puertas: 4,
    tipo: 'Sedán',
    caracteristicas: ['A/C', 'GPS', 'Bluetooth', 'Apple CarPlay', 'Cámara reversa'],
    badges: ['Disponible hoy', 'Verificado'],
    disponible: true,
    propietarioId: 'owner3',
  },
  {
    id: '11',
    marca: 'Mitsubishi',
    modelo: 'Outlander',
    anio: 2023,
    precio: 38,
    ubicacion: 'Antiguo Cuscatlán',
    distancia: 3.5,
    imagen: 'https://images.unsplash.com/photo-1568605117036-5fe5e7bab0b7?w=800&q=80',
    rating: 4.5,
    reviewCount: 41,
    transmision: 'Automático',
    combustible: 'Gasolina',
    pasajeros: 7,
    puertas: 4,
    tipo: 'SUV',
    caracteristicas: ['A/C', 'GPS', 'Bluetooth', '3era fila de asientos'],
    badges: ['Verificado'],
    disponible: true,
    propietarioId: 'owner7',
  },
  {
    id: '12',
    marca: 'Suzuki',
    modelo: 'Swift',
    anio: 2021,
    precio: 20,
    precioOriginal: 24,
    ubicacion: 'Soyapango',
    distancia: 6.8,
    imagen: 'https://images.unsplash.com/photo-1603584173870-7f23fdae1b7a?w=800&q=80',
    rating: 4.4,
    reviewCount: 29,
    transmision: 'Manual',
    combustible: 'Gasolina',
    pasajeros: 5,
    puertas: 4,
    tipo: 'Hatchback',
    caracteristicas: ['A/C', 'Bluetooth', 'USB'],
    badges: ['Descuento'],
    disponible: true,
    propietarioId: 'owner8',
  },
];

export const VEHICLE_TYPES = ['Todos', 'Sedán', 'SUV', 'Pickup', 'Hatchback', 'Minivan'];
export const TRANSMISION_TYPES = ['Todos', 'Automático', 'Manual'];
export const FUEL_TYPES = ['Todos', 'Gasolina', 'Diesel', 'Híbrido', 'Eléctrico'];
export const FEATURES = ['A/C', 'Bluetooth', 'GPS', 'Apple CarPlay', 'Android Auto', 'Cámara reversa', 'Cámara 360°', 'USB', 'Sensor de estacionamiento', 'Asientos de cuero', '3era fila de asientos'];
